### ISSUE TITLE
Table numbers increment incorrectly in table environment

### ISSUE THREAD

**Issue by azathoth246** [Ri-Ga/keyvaltable#3]
When declaring the caption in a table environment wrapping the keyvaltable, table numbers increment by 2. IE, the first declared table will display as Table 2 instead of Table 1.

**Comment by Ri-Ga** [comment]
Hi. Thanks for reporting the bug. The following example shows a correct table numbering for me:
```
\documentclass{article}
\usepackage{keyvaltable}
\NewKeyValTable{Test}{x; y}

\begin{document}
\begin{KeyValTable}[caption=Test,label=tab:Test1]{Test}
	\Row{x=1, y=2}
\end{KeyValTable}

\begin{KeyValTable}[caption=Test,label=tab:Test2]{Test}
	\Row{x=1, y=2}
\end{KeyValTable}
\end{document}
```
There was an issue with the xltabular package, which keyvaltable uses internally. If the above example produces wrong numbers for you, @azathoth246, could you please check which version of xltabular you are using? I am using v0.2d. If you are using an older version, could you please give it a try with the new version (see https://github.com/rolfn/xltabular)?

If the above example produces correct numbers, could you please share a working example that demonstrates the bug? Thanks!

**Comment by azathoth246** [comment]
Thank you for looking into this. Confirmed that I was using an older version of xltabular (v0.2c). Table numbering works correctly with v0.2d.
